-- Day 016: Business-Ready Output Practice
-- Topic: Turning raw columns into clear reporting outputs with SELECT.
-- These queries do not change the source tables.

-- 1. Business-ready customer output for a customer list.
SELECT customer_id, TRIM(customer_name) AS customer_name, LOWER(TRIM(email)) AS email, CASE WHEN UPPER(TRIM(country)) IN ('UK','U.K.','UNITED KINGDOM') THEN 'UK' WHEN UPPER(TRIM(country)) IN ('USA','U.S.A','UNITED STATES') THEN 'USA' WHEN UPPER(TRIM(country)) = 'INDIA' THEN 'India' WHEN UPPER(TRIM(country)) = 'CANADA' THEN 'Canada' WHEN UPPER(TRIM(country)) = 'GERMANY' THEN 'Germany' WHEN UPPER(TRIM(country)) = 'AUSTRALIA' THEN 'Australia' ELSE 'Unknown' END AS country, CASE WHEN LOWER(TRIM(customer_status)) = 'active' THEN 'Active' WHEN LOWER(TRIM(customer_status)) = 'inactive' THEN 'Inactive' WHEN LOWER(TRIM(customer_status)) = 'pending' THEN 'Pending' WHEN LOWER(TRIM(customer_status)) = 'blocked' THEN 'Blocked' ELSE 'Unknown' END AS customer_status, CASE WHEN LOWER(TRIM(marketing_opt_in)) IN ('true','yes','y') THEN 'true' WHEN LOWER(TRIM(marketing_opt_in)) IN ('false','no','n') THEN 'false' ELSE 'unknown' END AS marketing_opt_in FROM raw_customers;

-- 2. Business-ready order output for order monitoring.
SELECT order_id, customer_id, order_date, order_amount, CASE WHEN order_amount IS NULL THEN 'Unknown' WHEN order_amount < 50 THEN 'Low' WHEN order_amount >= 50 AND order_amount < 200 THEN 'Medium' WHEN order_amount >= 200 AND order_amount < 500 THEN 'High' ELSE 'Premium' END AS order_value_band, CASE WHEN LOWER(TRIM(order_status)) = 'created' THEN 'Created' WHEN LOWER(TRIM(order_status)) = 'shipped' THEN 'Shipped' WHEN LOWER(TRIM(order_status)) = 'delivered' THEN 'Delivered' WHEN LOWER(TRIM(order_status)) = 'cancelled' THEN 'Cancelled' WHEN LOWER(TRIM(order_status)) = 'returned' THEN 'Returned' ELSE 'Unknown' END AS order_status, CASE WHEN LOWER(TRIM(payment_status)) = 'paid' THEN 'Paid' WHEN LOWER(TRIM(payment_status)) = 'pending' THEN 'Pending' WHEN LOWER(TRIM(payment_status)) = 'failed' THEN 'Failed' WHEN LOWER(TRIM(payment_status)) = 'refunded' THEN 'Refunded' ELSE 'Unknown' END AS payment_status FROM raw_orders;

-- 3. Business-ready product output for a product catalogue.
SELECT product_id, TRIM(product_name) AS product_name, CASE WHEN LOWER(TRIM(category)) = 'electronics' THEN 'Electronics' WHEN LOWER(TRIM(category)) = 'books' THEN 'Books' WHEN LOWER(TRIM(category)) = 'home' THEN 'Home' WHEN LOWER(TRIM(category)) = 'clothing' THEN 'Clothing' WHEN LOWER(TRIM(category)) = 'sports' THEN 'Sports' WHEN LOWER(TRIM(category)) = 'beauty' THEN 'Beauty' ELSE 'Unknown' END AS category, price, CASE WHEN price IS NULL THEN 'Unknown' WHEN price < 20 THEN 'Low' WHEN price >= 20 AND price < 100 THEN 'Medium' WHEN price >= 100 AND price < 300 THEN 'High' ELSE 'Premium' END AS price_band, CASE WHEN LOWER(TRIM(is_active)) IN ('true','yes','y') THEN 'true' WHEN LOWER(TRIM(is_active)) IN ('false','no','n') THEN 'false' ELSE 'unknown' END AS is_active, CASE WHEN LOWER(TRIM(stock_status)) = 'in stock' THEN 'In Stock' WHEN LOWER(TRIM(stock_status)) = 'out of stock' THEN 'Out of Stock' WHEN LOWER(TRIM(stock_status)) = 'low stock' THEN 'Low Stock' WHEN LOWER(TRIM(stock_status)) = 'discontinued' THEN 'Discontinued' ELSE 'Unknown' END AS stock_status FROM raw_products;

-- 4. Business-ready campaign output for marketing planning.
SELECT campaign_id, TRIM(campaign_name) AS campaign_name, CASE WHEN LOWER(TRIM(channel)) = 'search' THEN 'Search' WHEN LOWER(TRIM(channel)) = 'social' THEN 'Social' WHEN LOWER(TRIM(channel)) = 'email' THEN 'Email' WHEN LOWER(TRIM(channel)) = 'display' THEN 'Display' WHEN LOWER(TRIM(channel)) = 'affiliate' THEN 'Affiliate' ELSE 'Unknown' END AS channel, CASE WHEN UPPER(TRIM(country)) IN ('UK','U.K.','UNITED KINGDOM') THEN 'UK' WHEN UPPER(TRIM(country)) IN ('USA','U.S.A','UNITED STATES') THEN 'USA' WHEN UPPER(TRIM(country)) = 'INDIA' THEN 'India' WHEN UPPER(TRIM(country)) = 'CANADA' THEN 'Canada' ELSE 'Unknown' END AS country, CASE WHEN LOWER(TRIM(campaign_status)) = 'active' THEN 'Active' WHEN LOWER(TRIM(campaign_status)) = 'paused' THEN 'Paused' WHEN LOWER(TRIM(campaign_status)) = 'completed' THEN 'Completed' WHEN LOWER(TRIM(campaign_status)) = 'cancelled' THEN 'Cancelled' ELSE 'Unknown' END AS campaign_status, budget, CASE WHEN budget IS NULL THEN 'Unknown' WHEN budget < 1000 THEN 'Small' WHEN budget >= 1000 AND budget < 5000 THEN 'Medium' ELSE 'Large' END AS budget_band FROM raw_campaigns;

-- 5. Business-ready campaign performance output for reporting.
SELECT performance_date, campaign_id, CASE WHEN LOWER(TRIM(channel)) = 'search' THEN 'Search' WHEN LOWER(TRIM(channel)) = 'social' THEN 'Social' WHEN LOWER(TRIM(channel)) = 'email' THEN 'Email' WHEN LOWER(TRIM(channel)) = 'display' THEN 'Display' WHEN LOWER(TRIM(channel)) = 'affiliate' THEN 'Affiliate' ELSE 'Unknown' END AS channel, CASE WHEN UPPER(TRIM(country)) IN ('UK','U.K.','UNITED KINGDOM') THEN 'UK' WHEN UPPER(TRIM(country)) IN ('USA','U.S.A','UNITED STATES') THEN 'USA' WHEN UPPER(TRIM(country)) = 'INDIA' THEN 'India' WHEN UPPER(TRIM(country)) = 'GERMANY' THEN 'Germany' ELSE 'Unknown' END AS country, impressions, clicks, cost, conversions, revenue, CASE WHEN cost IS NULL OR revenue IS NULL THEN 'Unknown' WHEN revenue = 0 THEN 'No Revenue' WHEN cost = 0 AND revenue > 0 THEN 'Check Cost Data' WHEN revenue > cost THEN 'Profitable' WHEN revenue = cost THEN 'Break Even' ELSE 'Needs Review' END AS performance_label FROM raw_campaign_performance;

-- 6. Customer dashboard preparation output.
SELECT customer_id, CASE WHEN LOWER(TRIM(customer_status)) = 'active' THEN 'Active' WHEN LOWER(TRIM(customer_status)) = 'inactive' THEN 'Inactive' WHEN LOWER(TRIM(customer_status)) = 'pending' THEN 'Pending' WHEN LOWER(TRIM(customer_status)) = 'blocked' THEN 'Blocked' ELSE 'Unknown' END AS customer_status, CASE WHEN LOWER(TRIM(marketing_opt_in)) IN ('true','yes','y') THEN 'Marketing Eligible' WHEN LOWER(TRIM(marketing_opt_in)) IN ('false','no','n') THEN 'Not Marketing Eligible' ELSE 'Unknown Eligibility' END AS marketing_eligibility FROM raw_customers;

-- 7. Order dashboard preparation output.
SELECT order_id, order_amount, CASE WHEN order_amount >= 500 THEN 'High Priority' WHEN order_amount >= 200 AND order_amount < 500 THEN 'Review' WHEN order_amount < 200 THEN 'Standard' ELSE 'Unknown' END AS order_priority, CASE WHEN LOWER(TRIM(payment_status)) = 'failed' THEN 'Payment Problem' WHEN LOWER(TRIM(order_status)) IN ('cancelled','returned') THEN 'Order Problem' WHEN LOWER(TRIM(payment_status)) = 'paid' THEN 'Paid Order' ELSE 'Review' END AS dashboard_order_label FROM raw_orders;

-- 8. Campaign dashboard preparation output.
SELECT campaign_id, budget, CASE WHEN budget >= 5000 THEN 'Major Campaign' WHEN budget >= 1000 AND budget < 5000 THEN 'Standard Campaign' WHEN budget < 1000 THEN 'Small Campaign' ELSE 'Unknown Campaign Size' END AS campaign_size_label, CASE WHEN LOWER(TRIM(campaign_status)) = 'active' THEN 'Live' WHEN LOWER(TRIM(campaign_status)) = 'paused' THEN 'Paused' WHEN LOWER(TRIM(campaign_status)) = 'completed' THEN 'Finished' ELSE 'Needs Review' END AS dashboard_campaign_status FROM raw_campaigns;

-- 9. Product reporting output.
SELECT product_id, TRIM(product_name) AS product_name, price, CASE WHEN price >= 300 THEN 'Premium Product' WHEN price >= 100 AND price < 300 THEN 'High Price Product' WHEN price >= 20 AND price < 100 THEN 'Standard Product' WHEN price < 20 THEN 'Entry Product' ELSE 'Unknown Price' END AS reporting_price_label, CASE WHEN LOWER(TRIM(stock_status)) = 'out of stock' THEN 'Cannot Sell' WHEN LOWER(TRIM(stock_status)) = 'discontinued' THEN 'Retired' WHEN LOWER(TRIM(is_active)) IN ('true','yes','y') THEN 'Available' ELSE 'Review' END AS product_reporting_status FROM raw_products;

-- 10. Data quality review output with raw and clean values side by side.
SELECT customer_id, country AS raw_country, CASE WHEN UPPER(TRIM(country)) IN ('UK','U.K.','UNITED KINGDOM') THEN 'UK' WHEN UPPER(TRIM(country)) IN ('USA','U.S.A','UNITED STATES') THEN 'USA' WHEN UPPER(TRIM(country)) = 'INDIA' THEN 'India' WHEN UPPER(TRIM(country)) = 'CANADA' THEN 'Canada' WHEN UPPER(TRIM(country)) = 'GERMANY' THEN 'Germany' WHEN UPPER(TRIM(country)) = 'AUSTRALIA' THEN 'Australia' ELSE 'Unknown' END AS clean_country, customer_status AS raw_customer_status, CASE WHEN LOWER(TRIM(customer_status)) = 'active' THEN 'Active' WHEN LOWER(TRIM(customer_status)) = 'inactive' THEN 'Inactive' WHEN LOWER(TRIM(customer_status)) = 'pending' THEN 'Pending' WHEN LOWER(TRIM(customer_status)) = 'blocked' THEN 'Blocked' ELSE 'Unknown' END AS clean_customer_status FROM raw_customers;
